const extractValueFromNotes = (notes, label) => {
  const escapedLabel = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = String(notes || '').match(new RegExp(`^${escapedLabel}:\\s*(.*)$`, 'mi'))
  return match?.[1]?.trim() || ''
}

const buildSalesExecutiveDataFromNotes = (lead) => ({
  contact: lead.phone || '',
  state: lead.state || '',
  city: lead.city || '',
  addressdu: lead.address || '',
  pincode: lead.pincode || '',
  branch: lead.branch || extractValueFromNotes(lead.notes, 'Branch'),
  panCardNo: extractValueFromNotes(lead.notes, 'PAN'),
  aadharNo: extractValueFromNotes(lead.notes, 'Aadhar'),
  dealNo: extractValueFromNotes(lead.notes, 'Deal No'),
  brand: extractValueFromNotes(lead.notes, 'Brand'),
  accountNo: extractValueFromNotes(lead.notes, 'Account No'),
  ifscCode: extractValueFromNotes(lead.notes, 'IFSC Code'),
  other: extractValueFromNotes(lead.notes, 'Other Details'),
  photoOneName: extractValueFromNotes(lead.notes, 'Photo 1 File') || extractValueFromNotes(lead.notes, 'Image File'),
  photoTwoName: extractValueFromNotes(lead.notes, 'Photo 2 File'),
  documentPdfName: extractValueFromNotes(lead.notes, 'PDF File'),
  aadharCardName: extractValueFromNotes(lead.notes, 'Aadhar Card File'),
  panCardName: extractValueFromNotes(lead.notes, 'PAN Card File'),
  bankStatementName: extractValueFromNotes(lead.notes, 'Bank Statement File'),
})

const getGeneratedByName = (lead) => {
  if (lead?.createdBy?.name) return lead.createdBy.name
  if (typeof lead?.createdBy === 'string') return lead.createdBy
  return ''
}

export const getSalesExecutiveData = (lead) => {
  const data = lead?.salesExecutiveData || {}
  const hasStructuredData = Object.values(data).some((value) => String(value || '').trim())

  return hasStructuredData ? data : buildSalesExecutiveDataFromNotes(lead || {})
}

export const getLeadViewSections = (lead) => {
  const salesExecutiveData = getSalesExecutiveData(lead)
  const dispatchItems = Array.isArray(lead?.dispatchData?.items) ? lead.dispatchData.items : []
  const dispatchItemsText = dispatchItems
    .map((item) => `${item.productName || item.category || 'Item'} - ${item.quantity || 0} ${item.unit || 'pcs'}`)
    .join(', ')
  const hasSalesExecutiveData = Object.values(salesExecutiveData).some((value) => String(value || '').trim())
  const isSalesExecutiveLead = (
    (Array.isArray(lead?.tags) && lead.tags.includes('sales-executive')) ||
    String(lead?.generatedThrough || '').toLowerCase().includes('sales executive') ||
    String(lead?.notes || '').toLowerCase().includes('sales executive registration') ||
    hasSalesExecutiveData
  )

  const overview = [
    ['ID', lead?._id?.slice(-8) || lead?.id || '-'],
    ['Customer', lead?.name || '-'],
    ['Phone', lead?.phone || '-'],
    ['Email', lead?.email || '-'],
    ['Address', lead?.address || salesExecutiveData.addressdu || '-'],
    ['City', lead?.city || salesExecutiveData.city || '-'],
    ['State', lead?.state || salesExecutiveData.state || '-'],
    ['Pincode', lead?.pincode || salesExecutiveData.pincode || '-'],
    ['Branch', lead?.branch || salesExecutiveData.branch || '-'],
    ['IVRS No.', lead?.ivrsNo || '-'],
    ['Source', lead?.source || '-'],
    ['Generated By', getGeneratedByName(lead) || '-'],
    ['By / Through', lead?.generatedThrough || '-'],
    ['Capacity', lead?.capacity || '-'],
    ['Roof Type', lead?.roofType || '-'],
    ['Monthly Bill', lead?.monthlyBill ? `Rs ${Number(lead.monthlyBill).toLocaleString('en-IN')}` : '-'],
    ['Assigned To', lead?.assignedTo?.name || lead?.assignedTo || '-'],
    ['Status', lead?.status || '-'],
  ]

  const salesExecutiveFields = isSalesExecutiveLead ? [
    ['Name', lead?.name || '-'],
    ['Email', lead?.email || '-'],
    ['Sales Contact', salesExecutiveData.contact || lead?.phone || '-'],
    ['State', salesExecutiveData.state || lead?.state || '-'],
    ['City', salesExecutiveData.city || lead?.city || '-'],
    ['Address', salesExecutiveData.addressdu || lead?.address || '-'],
    ['Pincode', salesExecutiveData.pincode || lead?.pincode || '-'],
    ['Branch', lead?.branch || salesExecutiveData.branch || '-'],
    ['Deal No.', salesExecutiveData.dealNo || '-'],
    ['Brand', salesExecutiveData.brand || '-'],
    ['Generated By', getGeneratedByName(lead) || '-'],
    ['Monthly Unit', salesExecutiveData.monthlyUnit || '-'],
    ['IVRS No.', lead?.ivrsNo || extractValueFromNotes(lead?.notes, 'IVRS No') || '-'],
    ['PAN Card No.', salesExecutiveData.panCardNo || '-'],
    ['Aadhar No.', salesExecutiveData.aadharNo || '-'],
    ['Account No.', salesExecutiveData.accountNo || '-'],
    ['IFSC Code', salesExecutiveData.ifscCode || '-'],
    ['Other', salesExecutiveData.other || '-'],
    ['Photo 1', salesExecutiveData.photoOneName || '-'],
    ['Photo 2', salesExecutiveData.photoTwoName || '-'],
    ['Document PDF', salesExecutiveData.documentPdfName || '-'],
    ['Aadhar Card', salesExecutiveData.aadharCardName || '-'],
    ['PAN Card', salesExecutiveData.panCardName || '-'],
    ['Bank Statement', salesExecutiveData.bankStatementName || '-'],
  ] : []

  const stageSpecificFields = [
    ['Dispatch Bill No.', lead?.dispatchData?.billNo || '-'],
    ['Dispatch Tracking ID', lead?.dispatchData?.trackingId || '-'],
    ['Dispatched Items', dispatchItemsText || '-'],
    ['Dispatched At', lead?.dispatchData?.dispatchedAt ? new Date(lead.dispatchData.dispatchedAt).toLocaleDateString('en-IN') : '-'],
    ['Bank Remark', lead?.bankData?.remark || '-'],
    ['Application ID', lead?.loanData?.applicationId || '-'],
    ['Panel Photo', lead?.installationData?.panelPhotoName || '-'],
    ['Panel Number', lead?.installationData?.panelNumber || '-'],
    ['Inverter Number', lead?.installationData?.inverterNumber || '-'],
    ['Inverter Brand', lead?.installationData?.brand || '-'],
    ['Inverter AC+DC Box Photo', lead?.installationData?.inverterBoxPhotoName || '-'],
    ['Earthing Photo', lead?.installationData?.earthingPhotoName || '-'],
    ['Column Concrete Photo', lead?.installationData?.columnConcretePhotoName || '-'],
    ['Customer Short Video', lead?.installationData?.customerShortVideoName || '-'],
    ['Installation Completed At', lead?.installationData?.installedAt ? new Date(lead.installationData.installedAt).toLocaleDateString('en-IN') : '-'],
    ['Meter Number', lead?.netMeteringData?.meterNumber || '-'],
    ['Net Metering PDF', lead?.netMeteringData?.pdfName || '-'],
    ['Net Metering Approved At', lead?.netMeteringData?.approvedAt ? new Date(lead.netMeteringData.approvedAt).toLocaleDateString('en-IN') : '-'],
    ['Subsidy Photo', lead?.subsidyData?.photoName || '-'],
    ['Subsidy Photo 2', lead?.subsidyData?.photoTwoName || '-'],
    ['Subsidy Approved At', lead?.subsidyData?.receivedAt ? new Date(lead.subsidyData.receivedAt).toLocaleDateString('en-IN') : '-'],
    ['Subsidy Reading Photo', lead?.subsidyReadingData?.photoName || '-'],
    ['Subsidy Reading Completed At', lead?.subsidyReadingData?.completedAt ? new Date(lead.subsidyReadingData.completedAt).toLocaleDateString('en-IN') : '-'],
  ]

  return { overview, salesExecutiveFields, stageSpecificFields, isSalesExecutiveLead, salesExecutiveData }
}
